/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.chrissytopher.pump;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import org.junit.jupiter.api.Test;

import com.chrissytopher.pump.proto.PumpMessage.Attachment;
import com.chrissytopher.pump.proto.PumpMessage.Message;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

class MessageTest {
    @Test void messageConstructionAndSerialization() throws IOException {
        Message message = ProtoConstructors.Message("Test Message", new String[] {"Chrissy", "Juniper"});
        assertEquals(message.getText(), "Test Message", "failed basic check");
        Message processedMessage = Message.parseFrom(Serialization.serializeMessage(message));
        assertEquals(processedMessage.getText(), message.getText(), "failed check after serialization");
    }

    @Test void attachmentSendTest() throws IOException {
        File file = File.createTempFile("test", ".txt", new File(System.getProperty("java.io.tmpdir")));
        FileWriter writer = new FileWriter(file);
        writer.write("test!");
        writer.close();
        Attachment attachment = ServerUtils.PostAttachment("https://pcs.chrissytopher.com", file);
        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder()
            .url(attachment.getUrl())
            .build();

        try (Response response = client.newCall(request).execute()) {
            assertEquals(response.code(), 200, "didn't post the attachment correctly");
        }
    }
}
